version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn add --frozen-lockfile --ignore-scripts=false --verbose sharp && yarn install && yarn dev"
    env_file:
      - .env

volumes:
  node_modules:
