version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URI: postgres://${POSTGRES_USER:-payloaduser}:${POSTGRES_PASSWORD:-payloadpass}@postgres:5432/${POSTGRES_DB:-payloadcms}
    networks:
      - app-network

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-payloadcms}
      POSTGRES_USER: ${POSTGRES_USER:-payloaduser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-payloadpass}
    networks:
      - app-network

volumes:
  data:
  node_modules:

networks:
  app-network:
    driver: bridge
